/**
 * تم‌ها و چیدمان‌های سایت — قابل انتخاب توسط ادمین.
 * این فایل هم در سرور و هم در کلاینت استفاده می‌شود (بدون وابستگی به Node).
 */

export const THEMES = {
  midnight: {
    id: 'midnight',
    label: 'نیمه‌شب (تیره لوکس)',
    mode: 'dark',
    vars: {
      '--bg': '#0b0d12',
      '--bg-soft': '#12151d',
      '--surface': '#171b25',
      '--surface-2': '#1f2431',
      '--border': '#2a3040',
      '--text': '#eef1f7',
      '--text-muted': '#98a1b5',
      '--primary': '#c8a24a',
      '--primary-contrast': '#0b0d12',
      '--primary-soft': 'rgba(200,162,74,.14)',
      '--accent': '#6f7ff2',
      '--success': '#34d399',
      '--danger': '#f87171',
      '--warning': '#fbbf24',
      '--radius': '16px',
      '--shadow': '0 20px 50px -20px rgba(0,0,0,.75)',
    },
  },
  ivory: {
    id: 'ivory',
    label: 'عاج (روشن مینیمال)',
    mode: 'light',
    vars: {
      '--bg': '#faf9f7',
      '--bg-soft': '#f3f1ed',
      '--surface': '#ffffff',
      '--surface-2': '#f6f5f2',
      '--border': '#e6e2db',
      '--text': '#1b1a18',
      '--text-muted': '#77726a',
      '--primary': '#1b1a18',
      '--primary-contrast': '#ffffff',
      '--primary-soft': 'rgba(27,26,24,.07)',
      '--accent': '#a1663a',
      '--success': '#16a34a',
      '--danger': '#dc2626',
      '--warning': '#d97706',
      '--radius': '14px',
      '--shadow': '0 18px 40px -24px rgba(20,18,14,.4)',
    },
  },
  rose: {
    id: 'rose',
    label: 'رز گلد (زنانه)',
    mode: 'light',
    vars: {
      '--bg': '#fffafb',
      '--bg-soft': '#fdeff2',
      '--surface': '#ffffff',
      '--surface-2': '#fdf3f5',
      '--border': '#f4dbe1',
      '--text': '#2b1d22',
      '--text-muted': '#8a6d75',
      '--primary': '#d6607f',
      '--primary-contrast': '#ffffff',
      '--primary-soft': 'rgba(214,96,127,.12)',
      '--accent': '#b98a5e',
      '--success': '#0f9d70',
      '--danger': '#e03e52',
      '--warning': '#e08a1e',
      '--radius': '20px',
      '--shadow': '0 18px 40px -22px rgba(180,80,110,.35)',
    },
  },
  ocean: {
    id: 'ocean',
    label: 'اقیانوس (آبی مدرن)',
    mode: 'light',
    vars: {
      '--bg': '#f6f9fc',
      '--bg-soft': '#eaf1f8',
      '--surface': '#ffffff',
      '--surface-2': '#f1f6fb',
      '--border': '#dbe6f0',
      '--text': '#0f1c2b',
      '--text-muted': '#5d7186',
      '--primary': '#1668cf',
      '--primary-contrast': '#ffffff',
      '--primary-soft': 'rgba(22,104,207,.10)',
      '--accent': '#0ea5a5',
      '--success': '#0e9f6e',
      '--danger': '#e02424',
      '--warning': '#c27803',
      '--radius': '12px',
      '--shadow': '0 16px 36px -22px rgba(15,40,80,.35)',
    },
  },
  forest: {
    id: 'forest',
    label: 'جنگل (سبز ارگانیک)',
    mode: 'light',
    vars: {
      '--bg': '#f7faf7',
      '--bg-soft': '#edf4ee',
      '--surface': '#ffffff',
      '--surface-2': '#f2f7f3',
      '--border': '#dbe7dd',
      '--text': '#12211a',
      '--text-muted': '#5f7369',
      '--primary': '#1f7a52',
      '--primary-contrast': '#ffffff',
      '--primary-soft': 'rgba(31,122,82,.11)',
      '--accent': '#9a7b2f',
      '--success': '#12855c',
      '--danger': '#d23b3b',
      '--warning': '#c98a12',
      '--radius': '14px',
      '--shadow': '0 16px 36px -22px rgba(20,60,40,.32)',
    },
  },
  noir: {
    id: 'noir',
    label: 'نوآر (سیاه‌وسفید)',
    mode: 'dark',
    vars: {
      '--bg': '#000000',
      '--bg-soft': '#0a0a0a',
      '--surface': '#121212',
      '--surface-2': '#1a1a1a',
      '--border': '#2b2b2b',
      '--text': '#f5f5f5',
      '--text-muted': '#9c9c9c',
      '--primary': '#ffffff',
      '--primary-contrast': '#000000',
      '--primary-soft': 'rgba(255,255,255,.10)',
      '--accent': '#c0c0c0',
      '--success': '#4ade80',
      '--danger': '#ff6b6b',
      '--warning': '#fbbf24',
      '--radius': '4px',
      '--shadow': '0 20px 40px -24px rgba(0,0,0,.9)',
    },
  },
  sunset: {
    id: 'sunset',
    label: 'غروب (نارنجی گرم)',
    mode: 'light',
    vars: {
      '--bg': '#fffaf5',
      '--bg-soft': '#fdf0e4',
      '--surface': '#ffffff',
      '--surface-2': '#fdf4ec',
      '--border': '#f2e0cf',
      '--text': '#261a10',
      '--text-muted': '#8a6f57',
      '--primary': '#e2621b',
      '--primary-contrast': '#ffffff',
      '--primary-soft': 'rgba(226,98,27,.12)',
      '--accent': '#b4315c',
      '--success': '#12946a',
      '--danger': '#d92d20',
      '--warning': '#d97706',
      '--radius': '18px',
      '--shadow': '0 18px 40px -22px rgba(160,80,20,.35)',
    },
  },
  violet: {
    id: 'violet',
    label: 'بنفش (تیره نئون)',
    mode: 'dark',
    vars: {
      '--bg': '#0d0a18',
      '--bg-soft': '#140f24',
      '--surface': '#1a1430',
      '--surface-2': '#221a3d',
      '--border': '#2f2550',
      '--text': '#f0ecff',
      '--text-muted': '#a297c9',
      '--primary': '#8b5cf6',
      '--primary-contrast': '#ffffff',
      '--primary-soft': 'rgba(139,92,246,.16)',
      '--accent': '#22d3ee',
      '--success': '#34d399',
      '--danger': '#fb7185',
      '--warning': '#fbbf24',
      '--radius': '18px',
      '--shadow': '0 20px 50px -22px rgba(80,40,160,.6)',
    },
  },
};

export const THEME_LIST = Object.values(THEMES);

/** چیدمان‌های کلی سایت */
export const LAYOUTS = {
  classic: {
    id: 'classic',
    label: 'کلاسیک — هدر ساده + گرید ۴ ستونه',
    heroStyle: 'split',
    productCard: 'standard',
    columns: 4,
    container: 'wide',
  },
  editorial: {
    id: 'editorial',
    label: 'مجله‌ای — بنر تمام‌عرض + کارت بلند',
    heroStyle: 'full',
    productCard: 'tall',
    columns: 3,
    container: 'wide',
  },
  minimal: {
    id: 'minimal',
    label: 'مینیمال — فضای سفید زیاد',
    heroStyle: 'center',
    productCard: 'minimal',
    columns: 3,
    container: 'narrow',
  },
  boutique: {
    id: 'boutique',
    label: 'بوتیک — کارت‌های فشرده و شلوغ',
    heroStyle: 'carousel',
    productCard: 'compact',
    columns: 5,
    container: 'full',
  },
};

export const LAYOUT_LIST = Object.values(LAYOUTS);

export const FONTS = {
  vazir: { id: 'vazir', label: 'وزیرمتن', stack: "'Vazirmatn', system-ui, sans-serif" },
  system: { id: 'system', label: 'سیستمی', stack: "system-ui, 'Segoe UI', Tahoma, sans-serif" },
};

export function themeCss(themeId, extra = {}) {
  const t = THEMES[themeId] || THEMES.midnight;
  const merged = { ...t.vars, ...extra };
  return Object.entries(merged)
    .map(([k, v]) => `${k}:${v}`)
    .join(';');
}
